export const GET_LAUNCH_LIST_REQUESTED = 'GET_LAUNCH_LIST_REQUESTED';
export const GET_LAUNCH_LIST_SUCCESS = 'GET_LAUNCH_LIST_SUCCESS';
export const GET_LAUNCH_LIST_ERRORED = 'GET_LAUNCH_LIST_ERRORED';